/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    esmExternals: 'loose',
  },
  transpilePackages: [
    '@ant-design/x',
    '@ant-design/icons',
    'antd',
    'rc-util',
    'rc-pagination',
    'rc-picker',
    'rc-notification',
    'rc-tooltip',
    'rc-tree',
    'rc-table',
    'rc-input',
    'rc-select',
    'rc-cascader',
    'rc-checkbox',
    'rc-dialog',
    'rc-drawer',
    'rc-dropdown',
    'rc-field-form',
    'rc-image',
    'rc-menu',
    'rc-motion',
    'rc-overflow',
    'rc-progress',
    'rc-rate',
    'rc-resize-observer',
    'rc-segmented',
    'rc-slider',
    'rc-steps',
    'rc-switch',
    'rc-tabs',
    'rc-tag',
    'rc-textarea',
    'rc-time-picker',
    'rc-transfer',
    'rc-tree-select',
    'rc-trigger',
    'rc-upload',
  ],
}

module.exports = nextConfig
